[project]
name = "fused-ssim"
version = "0.0.2"
dependencies = [
  "torch",
]

[build-system]
requires = ["setuptools", "wheel", "torch", "ninja", "numpy", "packaging"]
build-backend = "setuptools.build_meta"
